### ISSUE TITLE
Example not compiling with mbed-tools + CMake

### ISSUE THREAD

**Issue by LDong-Arm** [ARMmbed/mbed-os-example-for-azure#26]
### Description of defect

Mbed CLI 2 (mbed-tools and CMake support) has been in development for some time and seen some changes. Applications' CMake definitions need to be updated accordingly. Currently this example is unable to compile using the latest mbed-tools.

#### Target(s) affected by this defect ?

Any targets.

#### Toolchain(s) (name and version) displaying this defect ?

Any toolchains.

#### What version of Mbed-os are you using (tag or sha) ?

mbed-os-6.9.0

#### What version(s) of tools are you using. List all that apply (E.g. mbed-cli)

mbed-tools: 7.8.0

#### How is this defect reproduced ?

Compilation with
```
mbed-tools compile -t GCC_ARM -m DISCO_L475VG_IOT01A
```
fails.

**Comment by LDong-Arm** [comment]
@ARMmbed/mbed-os-core This PR is ready for review, thanks.

**Comment by ciarmcom** [comment]
Thank you for raising this detailed GitHub issue. I am now notifying our internal issue triagers. 
*Internal Jira reference: https://jira.arm.com/browse/IOTOSM-3796*

**Comment by LDong-Arm** [comment]
Fix merged
